services:
  backend:
    build:
      context: .
      dockerfile: backend/MainBackend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - sqlite-data:/app/database
    depends_on:
      - db-interaction

  currency-exchange:
    build:
      context: .
      dockerfile: backend/exchange/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - backend
    volumes:
    - fetchRates.js:backend/exchange/exchange_rates.json

  db-interaction:
    build:
      context: .
      dockerfile: backend/DB/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - sqlite-data:/backend/DB/Marketplace_DB.db

  frontend:
    build:
      context: ./vue-project  # Den Pfad zum vue-project-Ordner angeben
      dockerfile: Dockerfile   # Wenn das Dockerfile im vue-project-Ordner ist
    ports:
      - "8085:5000"  # serve läuft standardmäßig auf Port 5000
    depends_on:
      - backend

volumes:
  sqlite-data:
  fetchRates.js:
