services:
  backend:
    build:
      context: ./backend/MainBackend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db-interaction

  currency-exchange:
    build:
      context: ./backend/exchange
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - backend
    volumes:
    - fetchRates.js:/exchange_rates

  db-interaction:
    build:
      context: ./backend/DB
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - sqlite-data:/db

  frontend:
    build:
      context: ./vue-project  # Den Pfad zum vue-project-Ordner angeben
      dockerfile: Dockerfile   # Wenn das Dockerfile im vue-project-Ordner ist
    ports:
      - "8085:5000"  # serve läuft standardmäßig auf Port 5000
    depends_on:
      - backend

volumes:
  sqlite-data:
  fetchRates.js:
