services:
  backend:
    build:
      context: .
      dockerfile: backend/MainBackend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - sqlite-data:/app/database
    depends_on:
      - db-interaction

  currency-exchange:
    build:
      context: .
      dockerfile: backend/exchange/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - backend

  db-interaction:
    build:
      context: .
      dockerfile: backend/DB/Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - sqlite-data:/app/database

  frontend:
    build:
      context: ./vue-project  # Den Pfad zum vue-project-Ordner angeben
      dockerfile: Dockerfile   # Wenn das Dockerfile im vue-project-Ordner ist
    ports:
      - "8085:5000"  # serve läuft standardmäßig auf Port 5000
    depends_on:
      - backend

volumes:
  sqlite-data:
