services:
  backend:
    build:
      context: ./backend/MainBackend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db-interaction

  currency-exchange:
    build:
      context: ./backend/exchange
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - backend
    volumes:
      - exchange-data:/exchange_rates

  db-interaction:
    build:
      context: ./backend/DB
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - sqlite-data:/db

  frontend:
    build:
      context: ./vue-project
      dockerfile: Dockerfile
    ports:
      - "8085:5000"
    depends_on:
      - backend

volumes:
  sqlite-data:
  exchange-data:
