services:
  vue-app:
    build: 
      context: ./vue-project
      dockerfile: Dockerfile   
    volumes:
      - ./vue-project/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    restart: always