version: '3.8'
services:
  backend:
    build:
      context: backend/MainBackend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - sqlite-data:/app/database
    depends_on:
      - db-interaction

  currency-exchange:
    build:
      context: backend/exchange
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - backend

  db-interaction:
    build:
      context: backend/DB
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - sqlite-data:/app/database

  frontend:
    build:
      context: vue-project  # Points to the Vue.js project
      dockerfile: Dockerfile
    ports:
      - "8080:5000"
    depends_on:
      - backend

volumes:
  sqlite-data:
