services:
  backend:
    image: username/web-services-backend:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - sqlite-data:/app/database
    depends_on:
      - db-interaction

  currency-exchange:
    image: username/web-services-currency-exchange:latest
    restart: unless-stopped
    ports:
      - "5001:5001"
    depends_on:
      - backend

  db-interaction:
    image: username/web-services-db-interaction:latest
    restart: unless-stopped
    ports:
      - "5002:5002"
    volumes:
      - sqlite-data:/app/database

  frontend:
    image: username/web-services-frontend:latest
    restart: unless-stopped
    ports:
      - "8080:5000"  # serve läuft auf Port 5000
    depends_on:
      - backend

volumes:
  sqlite-data:
